### ISSUE TITLE
Use Scala code instead of shelling out to echo and base64?

### ISSUE THREAD

**Issue by nightscape** [ckipp01/mill-ci-release#40]
Hi @ckipp01,

I'm just trying to use this plugin on Windows where `echo` and `base64` are not natively available.
Would it be possible to use native Scala code for that?
Is using third-party libraries an option or would you be concerned about the necessity to download additional stuff?

Thank you for creating this!

**Comment by ckipp01** [comment]
Hey @nightscape!

> Would it be possible to use native Scala code for that?

So I'm definitely not opposed to doing it with native code. It exists the way it does now primarily because that was how it was done in [sbt-ci-release](https://github.com/sbt/sbt-ci-release) and much of this was straight just copied logic from there transferred to Mill. Since it's also sort of aimed at being used in GitHub actions I didn't see a large need to really think about windows support as I was pretty positive everyone would be defaulting to ubuntu to do the release anyways. Out of curiosity, what's your use-case that you need to use windows for the release?

> Is using third-party libraries an option or would you be concerned about the necessity to download additional stuff?

I typically (especially in plugins) really try to keep my dep tree small. Did you have something in mind?

**Comment by nightscape** [comment]
I'm just trying to get it to work on my Windows dev machine, so I can get it running locally first without going through the tedious "change, commit, push, wait for CI, wait for CI, wait for CI" cycle 😉 
I just implemented a pure Scala version, turns out it works without any external dependencies 🎉
