### ISSUE TITLE
Sonatype error

### ISSUE THREAD

**Issue by nefilim** [ckipp01/mill-ci-release#43]
Hi there - plugin worked great this morning until just recently, now failing twice in a row:

https://github.com/nefilim/mill-git-semver/actions/runs/3999928597/jobs/6864513019#step:4:950

Wondering if by any chance the Sonatype response has changed?

**Comment by ckipp01** [comment]
Hey @nefilim, thanks for the report. Sonatype has notoriously terribly error messages. I have a feeling if you logged in and looked I _think_ you might get a more useful error message. From a quick glance it looks like [this job](https://github.com/nefilim/mill-git-semver/actions/runs/3999928182/jobs/6864437520O) actually correctly released 0.2.3, but then it also tried to release it again in [here](https://github.com/nefilim/mill-git-semver/actions/runs/3999928597/jobs/6864513019), which will of course fail because you can't overwrite it in sonatype releases. I'm not fully sure what happened there. Did you commit and tag the same commit? I might be that the workflow you  have doesn't work great with https://github.com/lefou/mill-vcs-version, which is what mill-ci-release uses under the hood. Since you have a bunch of tags right in a row. For example I have a feeling that if you'd make a change, and push it up, then it'd correctly release a new snapshot.

**Comment by nefilim** [comment]
hi @ckipp01 - thanks for the quick feedback. I pushed `main` and then pushed the new tag seconds later. It failed with the same error it shows currently and then I reran the jobs and it failed again with the same error.

**Comment by nefilim** [comment]
looks like it failed again, just pushing another tag (no code changes): https://github.com/nefilim/mill-git-semver/actions/runs/4000261084/jobs/6865165550#step:4:888 🤔

**Comment by ckipp01** [comment]
Hey @nefilim, again, look at the version that it's attempting to publish, 0.2.3. You can't overwrite a version so this is expected to fail. Tagging a single commit multiple times will lead to issues as you're experiencing as well since it won't actually know what commit is meant. I'd recommend just adding another commit, pushing it, and seeing what happens. Don't tag anything yet, just push a new commit and see.

**Comment by nefilim** [comment]
oops, sorry not familiar with vcs-version, i thought it would have used the new tag i pushed `0.2.4` but apparently not so :)

**Comment by nefilim** [comment]
<img width="626" alt="Screenshot 2023-01-24 at 14 35 50" src="https://user-images.githubusercontent.com/992282/214426805-dd9eb625-f91c-468a-aa24-7ea03f75a008.png">

Got it :) Appreciate your input

**Comment by ckipp01** [comment]
Great, glad you got it figured out!
